# Generated by Django 3.0.5 on 2020-04-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField()),
                ('book_num', models.PositiveSmallIntegerField()),
                ('book', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQSn_PGAQyYvtHTjh61RcvlKIgtFDM2e0IWg8bRMUvS1Bo0_kY5&usqp=CAU')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_num', models.PositiveSmallIntegerField()),
                ('chapter', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT77EfsaCllx-L584gO4MMywRWSr9VyPJxYJhveXHYCppsPNgLP&usqp=CAU')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='script.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_num', models.PositiveSmallIntegerField()),
                ('verse', models.TextField()),
                ('image_url', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='script.Chapter')),
            ],
        ),
    ]
