# Generated by Django 3.0.5 on 2020-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQSn_PGAQyYvtHTjh61RcvlKIgtFDM2e0IWg8bRMUvS1Bo0_kY5&usqp=CAU', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image_url',
            field=models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT77EfsaCllx-L584gO4MMywRWSr9VyPJxYJhveXHYCppsPNgLP&usqp=CAU', null=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
